# Generated by Django 5.2.5 on 2025-10-15 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0007_rename_idcliente_cliente_id_and_more'),
        ('divisas', '0009_alter_limiteconfig_limite_diario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaNotificacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificaciones_activas', models.BooleanField(default=True, help_text='Indica si el cliente desea recibir notificaciones de cambio de tasa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_notificacion', to='clientes.cliente', verbose_name='Cliente')),
                ('divisas_suscritas', models.ManyToManyField(blank=True, help_text='Divisas de las que el cliente quiere recibir notificaciones', related_name='clientes_suscritos', to='divisas.divisa', verbose_name='Divisas suscritas')),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación de Cliente',
                'verbose_name_plural': 'Preferencias de Notificación de Clientes',
                'db_table': 'notificaciones_preferencia_cliente',
            },
        ),
        migrations.CreateModel(
            name='PreferenciaNotificacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificaciones_activas', models.BooleanField(default=True, help_text='Indica si el usuario desea recibir notificaciones de cambio de tasa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('divisas_suscritas', models.ManyToManyField(blank=True, help_text='Divisas de las que el usuario quiere recibir notificaciones', related_name='usuarios_suscritos', to='divisas.divisa', verbose_name='Divisas suscritas')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_notificacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación de Usuario',
                'verbose_name_plural': 'Preferencias de Notificación de Usuarios',
                'db_table': 'notificaciones_preferencia_usuario',
            },
        ),
    ]
