# Generated by Django 5.2.5 on 2025-10-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificaciontasacliente',
            options={'default_permissions': ('view', 'change'), 'verbose_name': 'Notificación de tasa de Cliente', 'verbose_name_plural': 'Notificación de tasa de Clientes'},
        ),
        migrations.AlterModelOptions(
            name='notificaciontasausuario',
            options={'default_permissions': ('view', 'change'), 'verbose_name': 'Notificación de Tasa de Usuario', 'verbose_name_plural': 'Notificación de Tasa de Usuarios'},
        ),
        migrations.AlterModelTable(
            name='notificaciontasacliente',
            table='notificaciones_tasa_cliente',
        ),
        migrations.AlterModelTable(
            name='notificaciontasausuario',
            table='notificaciones_tasa_usuario',
        ),
    ]
