# Generated by Django 5.2.5 on 2025-10-24 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0009_alter_limiteconfig_limite_diario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificaciones', '0002_alter_notificaciontasacliente_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionCambioTasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('suscripcion', 'Divisa suscrita'), ('transaccion_pendiente', 'Transacción pendiente')], max_length=32)),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=255)),
                ('tasa_compra_anterior', models.DecimalField(decimal_places=6, max_digits=15)),
                ('tasa_compra_nueva', models.DecimalField(decimal_places=6, max_digits=15)),
                ('tasa_venta_anterior', models.DecimalField(decimal_places=6, max_digits=15)),
                ('tasa_venta_nueva', models.DecimalField(decimal_places=6, max_digits=15)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_cambio_tasa', to='divisas.divisa', verbose_name='Divisa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_cambio_tasa', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación de cambio de tasa',
                'verbose_name_plural': 'Notificaciones de cambio de tasa',
                'db_table': 'notificaciones_cambio_tasa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notificacioncambiotasa',
            index=models.Index(fields=['usuario', 'is_read'], name='notificaci_usuario_93d557_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacioncambiotasa',
            index=models.Index(fields=['divisa'], name='notificaci_divisa_3d9d65_idx'),
        ),
    ]
