# Generated by Django 5.2.5 on 2025-10-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_notificacioncambiotasa'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificacioncambiotasa',
            new_name='notificacio_usuario_7bd49d_idx',
            old_name='notificaci_usuario_93d557_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacioncambiotasa',
            new_name='notificacio_divisa__5694fc_idx',
            old_name='notificaci_divisa_3d9d65_idx',
        ),
    ]
