# Generated by Django 5.2.5 on 2025-10-26 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0009_merge_20251023_2106'),
        ('divisas', '0009_alter_limiteconfig_limite_diario_and_more'),
        ('metodos_financieros', '0001_initial'),
        ('tauser', '0003_alter_tauser_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_use_operacion', 'Puede realizar operaciones de compra y venta')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=10)),
                ('tasa_aplicada', models.DecimalField(decimal_places=6, max_digits=15)),
                ('tasa_inicial', models.DecimalField(decimal_places=6, max_digits=15)),
                ('monto_origen', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_destino', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('fallida', 'Fallida')], default='pendiente', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='clientes.cliente')),
                ('divisa_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_destino', to='divisas.divisa')),
                ('divisa_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_origen', to='divisas.divisa')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_operadas', to=settings.AUTH_USER_MODEL)),
                ('metodo_financiero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metodos_financieros.metodofinanciero')),
                ('metodo_financiero_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metodos_financieros.metodofinancierodetalle')),
                ('tauser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='tauser.tauser')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
