# Generated by Django 5.2.5 on 2025-09-04 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('TRANSFERENCIA_BANCARIA', 'Transferencia Bancaria'), ('BILLETERA_DIGITAL', 'Billetera Digital'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('METALICO', 'Metalico'), ('CHEQUE', 'Cheque')], max_length=50, unique=True)),
                ('permite_cobro', models.BooleanField(default=True, help_text='Casa puede cobrar con este método')),
                ('permite_pago', models.BooleanField(default=True, help_text='Casa puede pagar con este método')),
                ('comision_cobro_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('comision_pago_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Método Financiero',
                'verbose_name_plural': 'Métodos Financieros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_emisor', models.CharField(max_length=100)),
                ('titular', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('NORMAL', 'Cheque Normal'), ('ADELANTADO', 'Cheque Adelantado')], max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('COBRADO', 'Cobrado')], default='PENDIENTE', max_length=15)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Cheque',
                'verbose_name_plural': 'Cheques',
            },
        ),
        migrations.CreateModel(
            name='MetodoFinancieroDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_cuenta_casa', models.BooleanField(default=False, help_text='Indica si es cuenta de la casa de cambio')),
                ('alias', models.CharField(help_text='Nombre identificativo del método', max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('metodo_financiero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operaciones.metodofinanciero')),
            ],
            options={
                'verbose_name': 'Detalle de Método Financiero',
                'verbose_name_plural': 'Detalles de Métodos Financieros',
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('titular', models.CharField(max_length=100)),
                ('cbu_cvu', models.CharField(blank=True, help_text='CBU o CVU', max_length=22)),
                ('metodo_financiero_detalle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_bancaria', to='operaciones.metodofinancierodetalle')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
            },
        ),
        migrations.CreateModel(
            name='BilleteraDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=50)),
                ('usuario_id', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('alias_billetera', models.CharField(blank=True, max_length=50)),
                ('metodo_financiero_detalle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billetera_digital', to='operaciones.metodofinancierodetalle')),
            ],
            options={
                'verbose_name': 'Billetera Digital',
                'verbose_name_plural': 'Billeteras Digitales',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('last4', models.CharField(max_length=4)),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('titular', models.CharField(max_length=100)),
                ('metodo_financiero_detalle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta', to='operaciones.metodofinancierodetalle')),
            ],
            options={
                'verbose_name': 'Tarjeta de Crédito/Débito',
                'verbose_name_plural': 'Tarjetas de Crédito/Débito',
            },
        ),
        migrations.AddIndex(
            model_name='metodofinancierodetalle',
            index=models.Index(fields=['cliente', 'is_active'], name='operaciones_cliente_c15e76_idx'),
        ),
        migrations.AddIndex(
            model_name='metodofinancierodetalle',
            index=models.Index(fields=['es_cuenta_casa', 'is_active'], name='operaciones_es_cuen_33accc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metodofinancierodetalle',
            unique_together={('cliente', 'alias')},
        ),
    ]
