# Generated by Django 5.2.5 on 2025-10-03 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0001_initial'),
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='metodo_financiero_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financiero.metodofinancierodetalle'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='metodo_financiero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financiero.metodofinanciero'),
        ),
    ]
