# Generated by Django 5.2.5 on 2025-09-05 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del banco (ej: Santander, Itaú, BBVA)', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el banco está disponible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='BilleteraDigitalCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la billetera (ej: PayPal, MercadoPago, Binance Pay, TigoMoney)', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la billetera está disponible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billetera Digital',
                'verbose_name_plural': 'Billeteras Digitales',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='cheque',
            name='banco_emisor',
            field=models.ForeignKey(help_text='Banco emisor del cheque', on_delete=django.db.models.deletion.PROTECT, to='operaciones.banco'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='banco',
            field=models.ForeignKey(help_text='Banco del catálogo', on_delete=django.db.models.deletion.PROTECT, to='operaciones.banco'),
        ),
        migrations.AlterField(
            model_name='billeteradigital',
            name='plataforma',
            field=models.ForeignKey(help_text='Billetera del catálogo', on_delete=django.db.models.deletion.PROTECT, to='operaciones.billeteradigitalcatalogo'),
        ),
    ]
