# Generated by Django 5.2.5 on 2025-09-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('operaciones', '0002_banco_billeteradigitalcatalogo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metodofinancierodetalle',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='metodofinancierodetalle',
            constraint=models.UniqueConstraint(condition=models.Q(('cliente__isnull', False)), fields=('cliente', 'alias'), name='unique_cliente_alias'),
        ),
    ]
