# Generated by Django 5.2.5 on 2025-10-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_transaccion_metodo_financiero_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
