# Generated by Django 5.2.5 on 2025-10-25 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='factura_emitida',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PagoStripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('funding', models.CharField(max_length=10)),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operaciones.transaccion')),
            ],
        ),
    ]
