# Generated by Django 5.2.5 on 2025-09-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_remove_old_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodofinancierodetalle',
            name='desactivado_por_catalogo',
            field=models.BooleanField(default=False, help_text='Indica si fue desactivado por desactivación de catálogo (banco/billetera digital)'),
        ),
    ]
