# Generated by Django 5.2.5 on 2025-09-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_metodofinancierodetalle_desactivado_por_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='cvu',
            field=models.CharField(default=2222222222, help_text='CVU del banco para transferencias interbancarias', max_length=22, unique=True),
            preserve_default=False,
        ),
    ]
