# Generated by Django 5.2.5 on 2025-11-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_transaccion_factura_emitida_pagostripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='precio_base',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
    ]
