# Generated by Django 5.2.5 on 2025-09-21 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_simulacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simulacion',
            options={'default_permissions': (), 'permissions': [('can_use_simulacion', 'Puede usar simulación de operaciones')]},
        ),
    ]
