# Generated by Django 5.2.5 on 2025-09-22 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_alter_simulacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billeteradigitalcatalogo',
            options={'ordering': ['nombre'], 'verbose_name': 'Catalogo  de Billetera Digital', 'verbose_name_plural': 'Billeteras Digitales'},
        ),
    ]
