# Generated by Django 5.2.5 on 2025-09-24 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0009_cheque_analista_cheque_divisa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaLocalCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Marca de la tarjeta (ej: Visa, Mastercard, American Express, Cabal)', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la marca está disponible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catálogo de Tarjeta Local',
                'verbose_name_plural': 'Catálogo de Tarjetas Locales',
                'ordering': ['marca'],
            },
        ),
        migrations.RenameField(
            model_name='tarjeta',
            old_name='stripe_payment_method_id',
            new_name='payment_method_id',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='tipo',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('STRIPE', 'Stripe')], default='STRIPE', max_length=10),
        ),
        migrations.CreateModel(
            name='TarjetaLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last4', models.CharField(help_text='Últimos 4 dígitos del PAN', max_length=4)),
                ('titular', models.CharField(max_length=100)),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('metodo_financiero_detalle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta_local', to='operaciones.metodofinancierodetalle')),
                ('marca', models.ForeignKey(help_text='Marca de tarjeta del catálogo', on_delete=django.db.models.deletion.PROTECT, to='operaciones.tarjetalocalcatalogo')),
            ],
            options={
                'verbose_name': 'Tarjeta Local',
                'verbose_name_plural': 'Tarjetas Locales',
            },
        ),
    ]
