# Generated by Django 5.2.5 on 2025-09-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_tarjetalocalcatalogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='comision_personalizada',
            field=models.BooleanField(default=False, help_text='Permite configurar comisión personalizada'),
        ),
        migrations.AddField(
            model_name='banco',
            name='comisiones',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión por defecto del banco (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='billeteradigitalcatalogo',
            name='comision_personalizada',
            field=models.BooleanField(default=False, help_text='Permite configurar comisión personalizada'),
        ),
        migrations.AddField(
            model_name='billeteradigitalcatalogo',
            name='comisiones',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión por defecto de la billetera (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='tarjetalocalcatalogo',
            name='comision_personalizada',
            field=models.BooleanField(default=False, help_text='Permite configurar comisión personalizada'),
        ),
        migrations.AddField(
            model_name='tarjetalocalcatalogo',
            name='comisiones',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión por defecto de la tarjeta (%)', max_digits=5),
        ),
    ]
