# Generated by Django 5.2.5 on 2025-09-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0011_banco_comision_personalizada_banco_comisiones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='cvu',
        ),
    ]
