# Generated by Django 5.2.5 on 2025-09-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0012_remove_banco_cvu'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='cvu',
            field=models.CharField(blank=True, help_text='CVU del banco para transferencias interbancarias', max_length=22, null=True, unique=True),
        ),
    ]
