# Generated by Django 5.2.5 on 2025-09-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0013_banco_cvu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='comision_personalizada',
        ),
        migrations.RemoveField(
            model_name='banco',
            name='comisiones',
        ),
        migrations.RemoveField(
            model_name='billeteradigitalcatalogo',
            name='comision_personalizada',
        ),
        migrations.RemoveField(
            model_name='billeteradigitalcatalogo',
            name='comisiones',
        ),
        migrations.RemoveField(
            model_name='tarjetalocalcatalogo',
            name='comision_personalizada',
        ),
        migrations.RemoveField(
            model_name='tarjetalocalcatalogo',
            name='comisiones',
        ),
        migrations.AddField(
            model_name='banco',
            name='comision_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión por defecto para operaciones de compra (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='banco',
            name='comision_personalizada_compra',
            field=models.BooleanField(default=False, help_text='Permite configurar comisión personalizada para compra'),
        ),
        migrations.AddField(
            model_name='banco',
            name='comision_personalizada_venta',
            field=models.BooleanField(default=False, help_text='Permite configurar comisión personalizada para venta'),
        ),
        migrations.AddField(
            model_name='banco',
            name='comision_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión por defecto para operaciones de venta (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='billeteradigitalcatalogo',
            name='comision_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión por defecto para operaciones de compra (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='billeteradigitalcatalogo',
            name='comision_personalizada_compra',
            field=models.BooleanField(default=False, help_text='Permite configurar comisión personalizada para compra'),
        ),
        migrations.AddField(
            model_name='billeteradigitalcatalogo',
            name='comision_personalizada_venta',
            field=models.BooleanField(default=False, help_text='Permite configurar comisión personalizada para venta'),
        ),
        migrations.AddField(
            model_name='billeteradigitalcatalogo',
            name='comision_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión por defecto para operaciones de venta (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='tarjetalocalcatalogo',
            name='comision_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión por defecto para operaciones de compra (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='tarjetalocalcatalogo',
            name='comision_personalizada_compra',
            field=models.BooleanField(default=False, help_text='Permite configurar comisión personalizada para compra'),
        ),
        migrations.AddField(
            model_name='tarjetalocalcatalogo',
            name='comision_personalizada_venta',
            field=models.BooleanField(default=False, help_text='Permite configurar comisión personalizada para venta'),
        ),
        migrations.AddField(
            model_name='tarjetalocalcatalogo',
            name='comision_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión por defecto para operaciones de venta (%)', max_digits=5),
        ),
    ]
