# Generated by Django 5.2.5 on 2025-09-26 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_categoriacliente_isactive'),
        ('divisas', '0009_alter_limiteconfig_limite_diario_and_more'),
        ('operaciones', '0014_remove_banco_comision_personalizada_and_more'),
        ('tauser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TarjetaLocalCatalogo',
            new_name='TarjetaCatalogo',
        ),
        migrations.AlterModelOptions(
            name='simulacion',
            options={'default_permissions': (), 'permissions': [('can_use_simulacion', 'Puede usar simulación de operaciones'), ('can_use_operacion', 'Puede realizar operaciones de compra y venta')]},
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operaciones.tarjetacatalogo'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=10)),
                ('tasa_aplicada', models.DecimalField(decimal_places=6, max_digits=15)),
                ('tasa_inicial', models.DecimalField(decimal_places=6, max_digits=15)),
                ('monto_origen', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_destino', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('fallida', 'Fallida')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='clientes.cliente')),
                ('divisa_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_destino', to='divisas.divisa')),
                ('divisa_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_origen', to='divisas.divisa')),
                ('metodo_financiero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.metodofinanciero')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_operadas', to=settings.AUTH_USER_MODEL)),
                ('tauser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='tauser.tauser')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TarjetaLocal',
        ),
    ]
