# Generated by Django 5.2.5 on 2025-09-25 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0014_remove_banco_comision_personalizada_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TarjetaLocalCatalogo',
            new_name='TarjetaCatalogo',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='marca',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='operaciones.tarjetacatalogo'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='brand',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.DeleteModel(
            name='TarjetaLocal',
        ),
    ]
