# Generated by Django 5.2.5 on 2025-09-25 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0015_rename_tarjetalocalcatalogo_tarjetacatalogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operaciones.tarjetacatalogo'),
        ),
    ]
