# Generated by Django 5.2.5 on 2025-09-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0015_transaccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simulacion',
            options={'default_permissions': (), 'permissions': [('can_use_simulacion', 'Puede usar simulación de operaciones'), ('can_use_operacion', 'Puede realizar operaciones de compra y venta')]},
        ),
    ]
