# Generated by Django 5.2.5 on 2025-10-12 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisas', '0009_alter_limiteconfig_limite_diario_and_more'),
        ('operaciones', '0002_transaccion_metodo_financiero_detalle_and_more'),
        ('tauser', '0003_alter_tauser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMovimiento',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=10, max_digits=30)),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='divisas.divisa')),
                ('tauser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tauser.tauser')),
                ('transaccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='operaciones.transaccion')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoStockDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='divisas.denominacion')),
                ('movimiento_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.movimientostock')),
            ],
        ),
        migrations.CreateModel(
            name='StockDivisaCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='divisas.denominacion', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockDivisaTauser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='divisas.denominacion')),
                ('tauser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tauser.tauser')),
            ],
        ),
    ]
