# Generated by Django 5.2.5 on 2025-10-12 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='estado',
            field=models.ForeignKey(default='EN_PROCESO', on_delete=django.db.models.deletion.PROTECT, to='stock.estadomovimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='tipo_movimiento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='stock.tipomovimiento'),
            preserve_default=False,
        ),
    ]
