# Generated by Django 5.2.5 on 2025-10-09 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0009_alter_limiteconfig_limite_diario_and_more'),
        ('stock', '0001_initial'),
        ('tauser', '0003_alter_tauser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientostock',
            name='stock_divisa_casa',
        ),
        migrations.AlterField(
            model_name='stockdivisacasa',
            name='denominacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='divisas.denominacion', unique=True),
        ),
        migrations.AlterField(
            model_name='stockdivisatauser',
            name='tauser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tauser.tauser', unique=True),
        ),
        migrations.AlterField(
            model_name='tipomovimiento',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
