# Generated by Django 5.2.5 on 2025-10-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0009_alter_limiteconfig_limite_diario_and_more'),
        ('stock', '0001_initial'),
        ('tauser', '0003_alter_tauser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdivisatauser',
            options={'verbose_name': 'Stock de Divisa en Tauser', 'verbose_name_plural': 'Stocks de Divisas en Tausers'},
        ),
        migrations.AlterUniqueTogether(
            name='stockdivisatauser',
            unique_together={('tauser', 'denominacion')},
        ),
    ]
