# Generated by Django 5.2.5 on 2025-10-09 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_movimientostock_stock_divisa_casa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stock.estadomovimiento'),
            preserve_default=False,
        ),
    ]
