# Generated by Django 5.2.5 on 2025-11-16 16:18

import apps.stock.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0009_alter_limiteconfig_limite_diario_and_more'),
        ('operaciones', '0004_transaccion_factura_emitida_pagostripe'),
        ('stock', '0002_add_unique_constraint_tauser_denominacion'),
        ('tauser', '0003_alter_tauser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='estado',
            field=models.CharField(choices=[(apps.stock.enums.EstadoMovimiento['EN_PROCESO'], 'Movimiento de stock en proceso'), (apps.stock.enums.EstadoMovimiento['FINALIZADO'], 'Movimiento de stock finalizado'), (apps.stock.enums.EstadoMovimiento['CANCELADO'], 'Movimiento de stock cancelado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo_movimiento',
            field=models.CharField(choices=[(apps.stock.enums.TipoMovimiento['SALCLT'], 'Salida de stock para el cliente'), (apps.stock.enums.TipoMovimiento['ENTCLT'], 'Entrada de stock del cliente'), (apps.stock.enums.TipoMovimiento['SALCS'], 'Salida de stock para la casa'), (apps.stock.enums.TipoMovimiento['ENTCS'], 'Entrada de stock para la casa')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='movimientostock',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_movimiento__in', [apps.stock.enums.TipoMovimiento['SALCLT'], apps.stock.enums.TipoMovimiento['ENTCLT'], apps.stock.enums.TipoMovimiento['SALCS'], apps.stock.enums.TipoMovimiento['ENTCS']])), name='stock_movimientostock_tipo_movimiento_check'),
        ),
        migrations.AddConstraint(
            model_name='movimientostock',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', [apps.stock.enums.EstadoMovimiento['EN_PROCESO'], apps.stock.enums.EstadoMovimiento['FINALIZADO'], apps.stock.enums.EstadoMovimiento['CANCELADO']])), name='stock_movimientostock_estado_check'),
        ),
        migrations.DeleteModel(
            name='EstadoMovimiento',
        ),
        migrations.DeleteModel(
            name='TipoMovimiento',
        ),
    ]
