# Generated by Django 5.2.5 on 2025-10-09 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0009_alter_limiteconfig_limite_diario_and_more'),
        ('stock', '0003_estadomovimiento_movimientostock_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='divisa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='divisas.divisa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='monto',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=30),
            preserve_default=False,
        ),
    ]
