# Generated by Django 5.2.5 on 2025-10-09 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_movimientostock_divisa_movimientostock_monto'),
        ('tauser', '0003_alter_tauser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdivisatauser',
            name='tauser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tauser.tauser'),
        ),
    ]
