# Generated by Django 5.2.5 on 2025-10-23 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metodos_financieros', '0003_tarjeta_funding_tarjeta_stripe_customer_id_and_more'),
        ('operaciones', '0003_transaccion_stripe_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metodos_financieros.metodofinanciero')),
                ('transaccion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='operaciones.transaccion')),
            ],
        ),
    ]
