# Generated by Django 5.2.5 on 2025-10-23 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_transaccion_stripe_session_id'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operaciones.transaccion'),
        ),
    ]
