FROM python:3.13.5-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -M -s /usr/sbin/nologin django


COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . /app

RUN chown -R django:django /app
USER django

