# Generated by Django 5.2.5 on 2025-09-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_assign_clients', 'Puede asignar clientes a usuarios'), ('can_assign_roles', 'Puede asignar roles a usuarios'), ('can_use_simulacion', 'Puede acceder a la simulacion de operaciones privada')]},
        ),
    ]
