# Generated by Django 5.2.5 on 2025-09-13 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_assign_clients', 'Puede asignar clientes a usuarios'), ('can_assign_roles', 'Puede asignar roles a usuarios')]},
        ),
    ]
