# Generated by Django 5.2.5 on 2025-09-24 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_categoriacliente_isactive'),
        ('usuarios', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clienteActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_cliente_actual', to='clientes.cliente'),
        ),
    ]
