# Generated by Django 5.2.5 on 2025-10-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_user_mfa_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='Indica si el usuario tiene autenticación de dos factores habilitada'),
        ),
    ]
