# Generated by Django 5.2.5 on 2025-09-02 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisas', '0006_remove_denominacion_pk_denominacion_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioBase', models.DecimalField(decimal_places=10, max_digits=30)),
                ('comisionBase', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('activo', models.BooleanField(default=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('divisa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tasa', to='divisas.divisa')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialTasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('tasaCompra', models.DecimalField(decimal_places=10, max_digits=30)),
                ('tasaVenta', models.DecimalField(decimal_places=10, max_digits=30)),
                ('tasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='cotizaciones.tasa')),
            ],
        ),
    ]
