# Generated by Django 5.2.5 on 2025-09-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasa',
            old_name='comisionBase',
            new_name='comisionBaseCompra',
        ),
        migrations.AddField(
            model_name='tasa',
            name='comisionBaseVenta',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
    ]
