# Generated by Django 5.2.5 on 2025-11-20 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisas', '0009_alter_limiteconfig_limite_diario_and_more'),
        ('metodos_financieros', '0002_cheque_transaccion'),
        ('operaciones', '0004_transaccion_factura_emitida_pagostripe'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosGanancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_view_ganancias', 'Puede ver reportes de ganancias')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Ganancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganancia_neta', models.DecimalField(decimal_places=2, help_text='Ganancia total neta de la operación', max_digits=15)),
                ('ganancia_margen_tasa', models.DecimalField(decimal_places=2, help_text='Ganancia por margen en la tasa de cambio', max_digits=15)),
                ('ganancia_comision_metodo', models.DecimalField(decimal_places=2, default=0, help_text='Ganancia por comisión del método de pago', max_digits=15)),
                ('descuento_categoria', models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado por categoría del cliente (valor negativo)', max_digits=15)),
                ('fecha', models.DateField(db_index=True, help_text='Fecha de la operación (sin hora)', verbose_name='Fecha')),
                ('anio', models.IntegerField(db_index=True, help_text='Año de la operación', verbose_name='Año')),
                ('mes', models.IntegerField(db_index=True, help_text='Mes de la operación (1-12)', verbose_name='Mes')),
                ('operacion', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], db_index=True, help_text='Tipo de operación desde perspectiva de la casa', max_length=10, verbose_name='Tipo de Operación')),
                ('tasa_mercado', models.DecimalField(decimal_places=6, help_text='Tasa base (precioBase) al momento de la operación', max_digits=15, verbose_name='Tasa de Mercado')),
                ('tasa_aplicada', models.DecimalField(decimal_places=6, help_text='Tasa final aplicada al cliente', max_digits=15, verbose_name='Tasa Aplicada')),
                ('monto_divisa', models.DecimalField(decimal_places=2, help_text='Monto en divisa extranjera de la operación', max_digits=15, verbose_name='Monto en Divisa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('divisa_extranjera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganancias', to='divisas.divisa', verbose_name='Divisa Extranjera')),
                ('metodo_financiero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ganancias', to='metodos_financieros.metodofinanciero', verbose_name='Método Financiero')),
                ('transaccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ganancia', to='operaciones.transaccion', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Ganancia',
                'verbose_name_plural': 'Ganancias',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['fecha', 'divisa_extranjera'], name='idx_fecha_divisa'), models.Index(fields=['anio', 'mes'], name='idx_anio_mes'), models.Index(fields=['metodo_financiero', 'fecha'], name='idx_metodo_fecha'), models.Index(fields=['operacion', 'fecha'], name='idx_operacion_fecha'), models.Index(fields=['divisa_extranjera', 'operacion', 'fecha'], name='idx_div_op_fecha')],
            },
        ),
    ]
