# Generated by Django 5.2.5 on 2025-11-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganancias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ganancia',
            name='descuento_categoria',
        ),
        migrations.RemoveField(
            model_name='ganancia',
            name='ganancia_comision_metodo',
        ),
        migrations.RemoveField(
            model_name='ganancia',
            name='ganancia_margen_tasa',
        ),
        migrations.AlterField(
            model_name='ganancia',
            name='ganancia_neta',
            field=models.DecimalField(decimal_places=2, help_text='Ganancia neta por la operación', max_digits=15),
        ),
    ]
