# Generated by Django 5.2.5 on 2025-10-02 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0005_categoriacliente_isactive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del banco (ej: Santander, Itaú, BBVA)', max_length=100, unique=True)),
                ('cvu', models.CharField(blank=True, help_text='CVU del banco para transferencias interbancarias', max_length=22, null=True, unique=True)),
                ('comision_compra', models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión por defecto para operaciones de compra (%)', max_digits=5)),
                ('comision_venta', models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión por defecto para operaciones de venta (%)', max_digits=5)),
                ('comision_personalizada_compra', models.BooleanField(default=False, help_text='Permite configurar comisión personalizada para compra')),
                ('comision_personalizada_venta', models.BooleanField(default=False, help_text='Permite configurar comisión personalizada para venta')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el banco está disponible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='BilleteraDigitalCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la billetera (ej: PayPal, MercadoPago, Binance Pay, TigoMoney)', max_length=100, unique=True)),
                ('comision_compra', models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión por defecto para operaciones de compra (%)', max_digits=5)),
                ('comision_venta', models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión por defecto para operaciones de venta (%)', max_digits=5)),
                ('comision_personalizada_compra', models.BooleanField(default=False, help_text='Permite configurar comisión personalizada para compra')),
                ('comision_personalizada_venta', models.BooleanField(default=False, help_text='Permite configurar comisión personalizada para venta')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la billetera está disponible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catalogo  de Billetera Digital',
                'verbose_name_plural': 'Billeteras Digitales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MetodoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('TRANSFERENCIA_BANCARIA', 'Transferencia Bancaria'), ('BILLETERA_DIGITAL', 'Billetera Digital'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque')], max_length=50, unique=True)),
                ('permite_cobro', models.BooleanField(default=True, help_text='Casa puede cobrar con este método')),
                ('permite_pago', models.BooleanField(default=True, help_text='Casa puede pagar con este método')),
                ('comision_cobro_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('comision_pago_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Método Financiero',
                'verbose_name_plural': 'Métodos Financieros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TarjetaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Marca de la tarjeta (ej: Visa, Mastercard, American Express, Cabal)', max_length=50, unique=True)),
                ('comision_compra', models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión por defecto para operaciones de compra (%)', max_digits=5)),
                ('comision_venta', models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión por defecto para operaciones de venta (%)', max_digits=5)),
                ('comision_personalizada_compra', models.BooleanField(default=False, help_text='Permite configurar comisión personalizada para compra')),
                ('comision_personalizada_venta', models.BooleanField(default=False, help_text='Permite configurar comisión personalizada para venta')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la marca está disponible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catálogo de Tarjeta Local',
                'verbose_name_plural': 'Catálogo de Tarjetas Locales',
                'ordering': ['marca'],
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('NORMAL', 'Cheque Normal'), ('ADELANTADO', 'Cheque Adelantado')], max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('divisa', models.CharField(choices=[('PYG', 'Guaraní'), ('USD', 'Dólar'), ('EUR', 'Euro')], default='PYG', max_length=3)),
                ('fecha_validacion_analista', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('banco_emisor', models.ForeignKey(help_text='Banco emisor del cheque', on_delete=django.db.models.deletion.PROTECT, to='metodos_financieros.banco')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Cheque',
                'verbose_name_plural': 'Cheques',
            },
        ),
        migrations.CreateModel(
            name='MetodoFinancieroDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_cuenta_casa', models.BooleanField(default=False, help_text='Indica si es cuenta de la casa de cambio')),
                ('alias', models.CharField(help_text='Nombre identificativo del método', max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('desactivado_por_catalogo', models.BooleanField(default=False, help_text='Indica si fue desactivado por desactivación de catálogo (banco/billetera digital)')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('metodo_financiero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metodos_financieros.metodofinanciero')),
            ],
            options={
                'verbose_name': 'Detalle de Método Financiero',
                'verbose_name_plural': 'Detalles de Métodos Financieros',
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('titular', models.CharField(max_length=100)),
                ('cbu_cvu', models.CharField(blank=True, help_text='CBU o CVU', max_length=22)),
                ('banco', models.ForeignKey(help_text='Banco del catálogo', on_delete=django.db.models.deletion.PROTECT, to='metodos_financieros.banco')),
                ('metodo_financiero_detalle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_bancaria', to='metodos_financieros.metodofinancierodetalle')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
            },
        ),
        migrations.CreateModel(
            name='BilleteraDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('alias_billetera', models.CharField(blank=True, max_length=50)),
                ('plataforma', models.ForeignKey(help_text='Billetera del catálogo', on_delete=django.db.models.deletion.PROTECT, to='metodos_financieros.billeteradigitalcatalogo')),
                ('metodo_financiero_detalle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billetera_digital', to='metodos_financieros.metodofinancierodetalle')),
            ],
            options={
                'verbose_name': 'Billetera Digital',
                'verbose_name_plural': 'Billeteras Digitales',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LOCAL', 'Local'), ('STRIPE', 'Stripe')], default='STRIPE', max_length=10)),
                ('payment_method_id', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('last4', models.CharField(max_length=4)),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('titular', models.CharField(max_length=100)),
                ('metodo_financiero_detalle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta', to='metodos_financieros.metodofinancierodetalle')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metodos_financieros.tarjetacatalogo')),
            ],
            options={
                'verbose_name': 'Tarjeta de Crédito/Débito',
                'verbose_name_plural': 'Tarjetas de Crédito/Débito',
            },
        ),
        migrations.AddIndex(
            model_name='metodofinancierodetalle',
            index=models.Index(fields=['cliente', 'is_active'], name='financiero__cliente_0500ab_idx'),
        ),
        migrations.AddIndex(
            model_name='metodofinancierodetalle',
            index=models.Index(fields=['es_cuenta_casa', 'is_active'], name='financiero__es_cuen_68b279_idx'),
        ),
        migrations.AddConstraint(
            model_name='metodofinancierodetalle',
            constraint=models.UniqueConstraint(condition=models.Q(('cliente__isnull', False)), fields=('cliente', 'alias'), name='unique_cliente_alias'),
        ),
    ]
