# Generated by Django 5.2.5 on 2025-10-05 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metodos_financieros', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='metodofinancierodetalle',
            new_name='metodos_fin_cliente_23e3d1_idx',
            old_name='financiero__cliente_0500ab_idx',
        ),
        migrations.RenameIndex(
            model_name='metodofinancierodetalle',
            new_name='metodos_fin_es_cuen_d2e6c2_idx',
            old_name='financiero__es_cuen_68b279_idx',
        ),
    ]
