# Generated by Django 5.2.5 on 2025-10-31 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodos_financieros', '0001_initial'),
        ('operaciones', '0004_transaccion_factura_emitida_pagostripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='transaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operaciones.transaccion'),
        ),
    ]
