# Generated by Django 5.2.5 on 2025-10-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodos_financieros', '0002_rename_financiero__cliente_0500ab_idx_metodos_fin_cliente_23e3d1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='funding',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metodofinanciero',
            name='nombre',
            field=models.CharField(choices=[('TRANSFERENCIA_BANCARIA', 'Transferencia Bancaria'), ('BILLETERA_DIGITAL', 'Billetera Digital'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('STRIPE', 'Stripe')], max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='tarjeta',
            index=models.Index(fields=['stripe_customer_id'], name='metodos_fin_stripe__96aa96_idx'),
        ),
    ]
