# Generated by Django 5.2.5 on 2025-10-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodos_financieros', '0002_rename_financiero__cliente_0500ab_idx_metodos_fin_cliente_23e3d1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodofinanciero',
            name='nombre',
            field=models.CharField(choices=[('TRANSFERENCIA_BANCARIA', 'Transferencia Bancaria'), ('BILLETERA_DIGITAL', 'Billetera Digital'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('STRIPE', 'Stripe')], max_length=50, unique=True),
        ),
    ]
