# Generated by Django 5.2.5 on 2025-10-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metodos_financieros', '0003_alter_metodofinanciero_nombre'),
        ('metodos_financieros', '0003_tarjeta_funding_tarjeta_stripe_customer_id_and_more'),
    ]

    operations = [
    ]
