# Generated by Django 5.2.5 on 2025-10-24 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0004_transaccion_factura_emitida_pagostripe'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_num', models.IntegerField(default=201)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('rango_inicio', models.IntegerField(default=201)),
                ('rango_fin', models.IntegerField(default=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_url', models.CharField(max_length=200)),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operaciones.transaccion')),
            ],
        ),
    ]
