# Generated by Django 5.2.5 on 2025-10-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='pdf_url',
        ),
        migrations.AddField(
            model_name='factura',
            name='cdc',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EN_PROCESO', 'En proceso')], default='EN_PROCESO', max_length=100),
        ),
    ]
