# Generated by Django 5.2.5 on 2025-11-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_remove_factura_pdf_url_factura_cdc_factura_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturasettings',
            name='ultimo_num',
            field=models.IntegerField(default=214),
        ),
    ]
