# Generated by Django 5.2.5 on 2025-08-22 08:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('isPersonaFisica', models.BooleanField(default=True)),
                ('categoria', models.CharField(choices=[('VIP', 'VIP'), ('CORPORATIVO', 'Corporativo'), ('MINORISTA', 'Minorista')], max_length=20)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('isActive', models.BooleanField(default=True)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
    ]
