<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-09-04 20:45
=======
# Generated by Django 5.2.5 on 2025-09-04 15:05
>>>>>>> origin/develop

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCliente',
            fields=[
                ('idCategoria', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento en la comisión', max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='clientes.categoriacliente'),
        ),
    ]
