# Generated by Django 5.2.5 on 2025-09-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_seed_categorias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='categoria',
            new_name='idCategoria',
        ),
    ]
