# Generated by Django 5.2.5 on 2025-09-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_rename_categoria_cliente_idcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacliente',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
