# Generated by Django 5.2.5 on 2025-09-29 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_categoriacliente_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriacliente',
            old_name='idCategoria',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='categoriacliente',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='idCategoria',
            new_name='id_categoria',
        ),
    ]
