# Generated by Django 5.2.5 on 2025-10-05 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_rename_idcategoria_categoriacliente_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='idCliente',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='isPersonaFisica',
            new_name='is_persona_fisica',
        ),
    ]
