# Generated by Django 5.2.5 on 2025-10-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_rename_idcliente_cliente_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='stripe_customer_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
