# Generated by Django 5.2.5 on 2025-10-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_rename_idcliente_cliente_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='gasto_diario',
            field=models.DecimalField(decimal_places=10, default=0.0, help_text='Gasto diario acumulado en divisa base', max_digits=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='gasto_mensual',
            field=models.DecimalField(decimal_places=10, default=0.0, help_text='Gasto mensualacumulado en divisa base', max_digits=30),
        ),
    ]
