# Generated by Django 5.2.5 on 2025-10-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_cliente_gasto_diario_cliente_gasto_mensual'),
        ('clientes', '0008_cliente_stripe_customer_id'),
    ]

    operations = [
    ]
