# Generated by Django 5.2.5 on 2025-10-31 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_merge_20251023_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_contribuyente',
            field=models.BooleanField(default=False),
        ),
    ]
