# Generated by Django 5.2.5 on 2025-08-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True, verbose_name='Código de divisa')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre de la divisa')),
                ('simbolo', models.CharField(max_length=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
