# Generated by Django 5.2.5 on 2025-08-29 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisa',
            name='max_digitos',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='divisa',
            name='precision',
            field=models.IntegerField(default=6),
        ),
        migrations.CreateModel(
            name='Denominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='divisas.divisa')),
            ],
        ),
    ]
