# Generated by Django 5.2.5 on 2025-08-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0002_divisa_max_digitos_divisa_precision_denominacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='denominacion',
            name='denominacion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
