# Generated by Django 5.2.5 on 2025-08-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0003_denominacion_denominacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='denominacion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
