# Generated by Django 5.2.5 on 2025-08-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0004_denominacion_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denominacion',
            name='id',
        ),
        migrations.AddField(
            model_name='denominacion',
            name='pk',
            field=models.CompositePrimaryKey('divisa_id', 'denominacion', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
