# Generated by Django 5.2.5 on 2025-08-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0005_remove_denominacion_id_denominacion_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denominacion',
            name='pk',
        ),
        migrations.AddField(
            model_name='denominacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
