# Generated by Django 5.2.5 on 2025-09-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0006_remove_denominacion_pk_denominacion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisa',
            name='es_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='divisa',
            constraint=models.UniqueConstraint(condition=models.Q(('es_base', True)), fields=('es_base',), name='unica_divisa_base'),
        ),
    ]
