# Generated by Django 5.2.5 on 2025-09-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0007_divisa_es_base_divisa_unica_divisa_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_diario', models.DecimalField(decimal_places=10, max_digits=30)),
                ('limite_mensual', models.DecimalField(decimal_places=10, max_digits=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
