# Generated by Django 5.2.5 on 2025-09-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0008_limiteconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limiteconfig',
            name='limite_diario',
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='limiteconfig',
            name='limite_mensual',
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True),
        ),
    ]
