# Generated by Django 5.2.5 on 2025-10-01 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tauser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tauser',
            old_name='idTauser',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tauser',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
