# Generated by Django 5.2.5 on 2025-10-04 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tauser', '0002_rename_idtauser_tauser_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tauser',
            options={'ordering': ['codigo']},
        ),
    ]
