# Generated by Django 5.2.5 on 2025-08-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
