name: Docker

on:
  push:
    branches: ["**"]
    tags: [ 'v*.*.*' ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME_FRONTEND: "frontend"
  IMAGE_NAME_BACKEND: "backend"


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Metadata Backend
      - name: Extract Docker metadata (backend)
        id: meta-backend
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME_BACKEND }}

      # Metadata Frontend
      - name: Extract Docker metadata (frontend)
        id: meta-frontend
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME_FRONTEND }}

      # Build backend
      - name: Build and push backend
        id: build-backend
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./backend
          file: ./backend/dockerfile
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      # Agregar el .env
      - name: Add .env.prod file
        run: |
          cat ${{ secrets.PROD_ENV }} > .env

      # Build frontend dist
      - name: Compilar el frontend
        run: |
          docker compose run --rm frontend npm run build

      # Build frontend (Nginx)
      - name: Build and push frontend
        id: build-frontend
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./nginx
          file: ./nginx/dockerfile
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Firmar backend
      - name: Sign backend image
        env:
          TAGS: ${{ steps.meta-backend.outputs.tags }}
          DIGEST: ${{ steps.build-backend.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      # Firmar frontend
      - name: Sign frontend image
        env:
          TAGS: ${{ steps.meta-frontend.outputs.tags }}
          DIGEST: ${{ steps.build-frontend.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
