name: Backend Tests

on:

  pull_request:
    branches:
      - '**'   # se ejecuta en cualquier PR

jobs:
  test:
    name: Ejecutar Tests Frontend
    runs-on: ubuntu-latest
    
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
        
      - name: Crear archivo .env a partir de secrets
        run: |
          # Variables de entorno para el backend
          echo "${{ secrets.DEV_ENV}}" > .env
          
      - name: Levantar contenedor frontend
        run: |
          docker compose up -d frontend
          
      - name: Ejecutar build dentro del contenedor
        run: |
          docker compose exec -T frontend npm run build
            
      - name: Limpiar contenedores de prueba
        if: always()
        run: |
          docker compose down --volumes --remove-orphans || true
          docker system prune -f || true
